// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UverTeaServerApp.Shared.Data;

#nullable disable

namespace UverTeaServerApp.Migrations
{
    [DbContext(typeof(UvaTeaDbContext))]
    partial class UvaTeaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Acres")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("acres");

                    b.Property<int>("AreaCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("areacategory_id");

                    b.Property<int>("AreaStatusId")
                        .HasColumnType("int")
                        .HasColumnName("areastatus_id");

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<DateOnly?>("DoAttached")
                        .HasColumnType("date")
                        .HasColumnName("doattached");

                    b.Property<DateOnly?>("DoProofing")
                        .HasColumnType("date")
                        .HasColumnName("doproofing");

                    b.Property<int?>("GrowthStageId")
                        .HasColumnType("int")
                        .HasColumnName("growthstage_id");

                    b.Property<int?>("PlantCount")
                        .HasColumnType("int")
                        .HasColumnName("plantcount");

                    b.Property<int?>("PlantingConfigurationId")
                        .HasColumnType("int")
                        .HasColumnName("plantingconfiguration_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AreaCategoryId");

                    b.HasIndex("AreaStatusId");

                    b.HasIndex("GrowthStageId");

                    b.HasIndex("PlantingConfigurationId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("UserId");

                    b.ToTable("area", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areacategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("areacategory", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areagrowthstagehistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Area_id")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<DateTime>("Changedat")
                        .HasColumnType("datetime2")
                        .HasColumnName("changedat");

                    b.Property<int>("Changedby")
                        .HasColumnType("int")
                        .HasColumnName("changedby");

                    b.Property<int>("From_growthstage_id")
                        .HasColumnType("int")
                        .HasColumnName("from_growthstage_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason");

                    b.Property<int>("To_growthstage_id")
                        .HasColumnType("int")
                        .HasColumnName("to_growthstage_id");

                    b.HasKey("Id");

                    b.HasIndex("Area_id");

                    b.HasIndex("Changedby");

                    b.HasIndex("From_growthstage_id");

                    b.HasIndex("To_growthstage_id");

                    b.ToTable("areagrowthstagehistory", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("areastatus", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatushistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Area_id")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<int?>("AreastatusId")
                        .HasColumnType("int");

                    b.Property<int?>("AreastatusId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Changedat")
                        .HasColumnType("datetime2")
                        .HasColumnName("changedat");

                    b.Property<int>("Changedby")
                        .HasColumnType("int")
                        .HasColumnName("changedby");

                    b.Property<int>("From_status_id")
                        .HasColumnType("int")
                        .HasColumnName("from_status_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason");

                    b.Property<int>("To_status_id")
                        .HasColumnType("int")
                        .HasColumnName("to_status_id");

                    b.HasKey("Id");

                    b.HasIndex("Area_id");

                    b.HasIndex("AreastatusId");

                    b.HasIndex("AreastatusId1");

                    b.HasIndex("Changedby");

                    b.HasIndex("From_status_id");

                    b.HasIndex("To_status_id");

                    b.ToTable("areastatushistory", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Growthstage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("Displayorder")
                        .HasColumnType("int")
                        .HasColumnName("displayorder");

                    b.Property<bool>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("growthstage", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Plantingconfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Plantspacingfeet")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("plantspacingfeet");

                    b.Property<decimal>("Rowspacingfeet")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("rowspacingfeet");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("plantingconfiguration", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("designation", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Callingname")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("callingname");

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int")
                        .HasColumnName("designation_id");

                    b.Property<DateOnly?>("Doassignment")
                        .HasColumnType("date")
                        .HasColumnName("doassignment");

                    b.Property<DateOnly?>("Dobirth")
                        .HasColumnType("date")
                        .HasColumnName("dobirth");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<int>("EmployeestatusId")
                        .HasColumnType("int")
                        .HasColumnName("employeestatus_id");

                    b.Property<string>("Fullname")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("fullname");

                    b.Property<int>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("gender_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Land")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("land");

                    b.Property<string>("Mobile")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("mobile")
                        .IsFixedLength();

                    b.Property<string>("Nic")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("nic");

                    b.Property<string>("Number")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .HasColumnName("number")
                        .IsFixedLength();

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DesignationId");

                    b.HasIndex("EmployeestatusId");

                    b.HasIndex("GenderId");

                    b.ToTable("employee", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Employeestatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("employeestatus", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("gender", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Operation");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Privilage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Authority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("OperationId");

                    b.HasIndex("RoleId");

                    b.ToTable("Privilage");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("role", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("Docreated")
                        .HasColumnType("date")
                        .HasColumnName("docreated");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<TimeOnly?>("Tocreated")
                        .HasColumnType("time")
                        .HasColumnName("tocreated");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedat");

                    b.Property<string>("Username")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("username");

                    b.Property<int>("UserstatusId")
                        .HasColumnType("int")
                        .HasColumnName("userstatus_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmployeeId" }, "fk_user_employee1_idx");

                    b.HasIndex(new[] { "RoleId" }, "fk_user_role1_idx");

                    b.HasIndex(new[] { "UserstatusId" }, "fk_user_userstatus1_idx");

                    b.ToTable("user", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Userstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("userstatus", "uvateafactory");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Area", b =>
                {
                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areacategory", "AreaCategory")
                        .WithMany("Areas")
                        .HasForeignKey("AreaCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatus", "AreaStatus")
                        .WithMany("Areas")
                        .HasForeignKey("AreaStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Growthstage", "GrowthStage")
                        .WithMany("Areas")
                        .HasForeignKey("GrowthStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Plantingconfiguration", "PlantingConfiguration")
                        .WithMany("Areas")
                        .HasForeignKey("PlantingConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Employee", "Supervisor")
                        .WithMany("Areas")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.User", "User")
                        .WithMany("Areas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaCategory");

                    b.Navigation("AreaStatus");

                    b.Navigation("GrowthStage");

                    b.Navigation("PlantingConfiguration");

                    b.Navigation("Supervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areagrowthstagehistory", b =>
                {
                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Area", "Area")
                        .WithMany("AreaGrowthStageHistories")
                        .HasForeignKey("Area_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.User", "ChangedbyNavigation")
                        .WithMany()
                        .HasForeignKey("Changedby")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Growthstage", "From_growthstage")
                        .WithMany("Areagrowthstagehistoryfrom_growthstages")
                        .HasForeignKey("From_growthstage_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Growthstage", "To_growthstage")
                        .WithMany("Areagrowthstagehistoryto_growthstages")
                        .HasForeignKey("To_growthstage_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ChangedbyNavigation");

                    b.Navigation("From_growthstage");

                    b.Navigation("To_growthstage");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatushistory", b =>
                {
                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Area", "Area")
                        .WithMany("AreaStatusHistories")
                        .HasForeignKey("Area_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatus", null)
                        .WithMany("Areastatushistoryfrom_statuses")
                        .HasForeignKey("AreastatusId");

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatus", null)
                        .WithMany("Areastatushistoryto_statuses")
                        .HasForeignKey("AreastatusId1");

                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.User", "ChangedbyNavigation")
                        .WithMany()
                        .HasForeignKey("Changedby")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatus", "From_status")
                        .WithMany()
                        .HasForeignKey("From_status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatus", "To_status")
                        .WithMany()
                        .HasForeignKey("To_status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ChangedbyNavigation");

                    b.Navigation("From_status");

                    b.Navigation("To_status");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Employee", b =>
                {
                    b.HasOne("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Employeestatus", "Employeestatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeestatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Gender", "Gender")
                        .WithMany("Employees")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Designation");

                    b.Navigation("Employeestatus");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Operation", b =>
                {
                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Module", "Module")
                        .WithMany("Operations")
                        .HasForeignKey("ModuleId");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Privilage", b =>
                {
                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Module", "Module")
                        .WithMany("Privilages")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Operation", "Operation")
                        .WithMany("Privilages")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Role", "Role")
                        .WithMany("Privilages")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Operation");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.User", b =>
                {
                    b.HasOne("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Employee", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_employee1");

                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role1");

                    b.HasOne("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Userstatus", "Userstatus")
                        .WithMany("Users")
                        .HasForeignKey("UserstatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_userstatus1");

                    b.Navigation("Employee");

                    b.Navigation("Role");

                    b.Navigation("Userstatus");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Area", b =>
                {
                    b.Navigation("AreaGrowthStageHistories");

                    b.Navigation("AreaStatusHistories");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areacategory", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Areastatus", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Areastatushistoryfrom_statuses");

                    b.Navigation("Areastatushistoryto_statuses");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Growthstage", b =>
                {
                    b.Navigation("Areagrowthstagehistoryfrom_growthstages");

                    b.Navigation("Areagrowthstagehistoryto_growthstages");

                    b.Navigation("Areas");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.AreaModule.Models.Entities.Plantingconfiguration", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Employee", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Employeestatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.EmployeeModule.Models.Entities.Gender", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Module", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("Privilages");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Operation", b =>
                {
                    b.Navigation("Privilages");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Role", b =>
                {
                    b.Navigation("Privilages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.User", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("UverTeaServerApp.src.Feature.UserModule.Models.Entities.Userstatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
